ep: &ep "01"  # 01 ~ 18
mode: subtitle  #demo or subtitle
output_dir: data/output
preprocessing:
    load: False
    substitle_file: !join ["data/input/AnotherMissOh_Scene_Subtitle/AnotherMissOh_ep", *ep, ".json"]
    output_path: !join ["data/output/ep", *ep, "_preprocessed.json"]
    coreference: gold

extraction:
    load: False
    oie: stanford
    frame: frameBERT
    output_path: !join ["data/output/ep", *ep, "_extracted.json"]

background:
    load: False
    input_path: data/background.txt
    output_path: data/output/background_KB.json

graph:
    character_name: data/character.txt
    use_backKB: True
    visualization: None  # all, frame, triple, None
    package_path: C:/Program Files (x86)/Graphviz2.38/bin/  # https://graphviz.gitlab.io/_pages/Download/Download_windows.html에서 설치 후 Graphviz 경로
    graph_path: data/output/graphs
    json_path: !join ["data/output/ep", *ep, "_graph.json"]
    character: all
    only_use: None
